name: Feature Request
description: Request a new feature for the sample handler.
labels: ["enhancement", "question"]
body:
  - type: markdown
    attributes:
      value: |
        > We can only implement features that Discord publishes, documents, and merges into the [Discord API documentation](https://discord.com/developers/docs/intro).
        We do not implement unreleased features, or features that are not disclosed in the [Discord API documentation](https://discord.com/developers/docs/intro).
  - type: textarea
    id: application_or_package
    attributes:
      label: Which part is this feature request for?
      description: Describe what segment of the template this feature should refer to.
      placeholder: This feature will bring my desire to lower Discord API ratelimits and make them static.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: Describe what the outcome should result in.
      placeholder: If an eval command was added, I can easily perform tasks from anywhere.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional_context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
  - type: markdown
    attributes:
      value: "Thank you for filling out this feature request!"
